### PR TITLE
changes for supporting upm

### PR DESCRIPTION
**Pull request by suntabu**
1. 使用了继承的方式来扩展ObjectTranslator
2. 通过Generator命令生成一个prefab，这个prefab挂载的脚本处理了从Assembly-Csharp中创建ObjectTranslatorExtensions的逻辑

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/xLua?pullRequest=747) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/xLua?pullRequest=747) before we can accept your contribution.<br/><hr/>**gouzhun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/xLua?pullRequest=747) it.</sub>

**Comment by chexiongsheng** [comment]
CI就没通过呢

**Comment by suntabu** [comment]
> CI就没通过呢

对的，我忘记用宏把Unity使用lua的情况和其他分开了。

**Comment by suntabu** [comment]
@chexiongsheng Unity方面运行的代码已经补齐运行正常了，其他XLUA_GENERAL的我不知道怎么修改。

**Pull request closed without merging**
