### PR TITLE
fixed the luacallcs tutorial can't run on mac issue

### PR DESCRIPTION
**Pull request by godotc03**
Mac 上 LuaCallCs Tutorial 编译不过，需要调整下代码顺序。

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/xLua?pullRequest=642) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/xLua?pullRequest=642) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/xLua?pullRequest=642) it.</sub>

**Comment by chexiongsheng** [comment]
不可能吧，按c#语法顺序应该不影响的，而且我mac是可以编译通过的
你的unity什么版本，编译报什么错误呢？

**Comment by godotc03** [comment]
理论上不应该受代码顺序影响，但我这边是这样，环境：Unity3D 2018.3.13 Mac OS: 10.13.6

**Comment by chexiongsheng** [comment]
我这重现不了，还是不调整了。

**Pull request closed without merging**
